apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: project
    type: frontend

spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: project
        type: frontend
    spec:
      containers:
        - name: frontend-container
          image: kkolodziejski/projectfrontend:latest

  replicas: 1
  selector:
    matchLabels:
      app: project
      type: frontend
